# Generated by Django 4.2.23 on 2025-08-14 00:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObraDeArte',
            fields=[
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Único')),
                ('numero_registro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Registro/Tombo')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('ano_producao', models.IntegerField(verbose_name='Ano de Produção')),
                ('data_producao_texto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Data de Produção (texto)')),
                ('timestamp_producao', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp da Produção (Data e Hora)')),
                ('tecnica_principal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Técnica Principal')),
                ('outras_tecnicas', models.TextField(blank=True, null=True, verbose_name='Outras Técnicas')),
                ('materiais_suporte', models.CharField(blank=True, max_length=255, null=True, verbose_name='Materiais/Suporte')),
                ('materiais_utilizados', models.TextField(blank=True, null=True, verbose_name='Materiais Utilizados')),
                ('dimensoes_altura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altura (cm)')),
                ('dimensoes_largura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Largura (cm)')),
                ('dimensoes_profundidade_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profundidade (cm)')),
                ('dimensoes_texto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dimensões (texto)')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso (kg)')),
                ('assinatura', models.CharField(blank=True, max_length=255, null=True, verbose_name='Assinatura')),
                ('inscricoes_marcas', models.TextField(blank=True, null=True, verbose_name='Inscrições/Marcas')),
                ('descricao_conceitual', models.TextField(blank=True, null=True, verbose_name='Descrição Conceitual')),
                ('descricao_iconografica', models.TextField(blank=True, null=True, verbose_name='Descrição Iconográfica')),
                ('palavras_chave', models.CharField(blank=True, max_length=500, null=True, verbose_name='Palavras-chave')),
                ('periodo_movimento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Período/Movimento')),
                ('geolocalizacao_producao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Geolocalização da Produção')),
                ('historico_exposicoes', models.TextField(blank=True, null=True, verbose_name='Histórico de Exposições')),
                ('proveniencia', models.TextField(blank=True, null=True, verbose_name='Proveniência')),
                ('bibliografia_publicacoes', models.TextField(blank=True, null=True, verbose_name='Bibliografia/Publicações')),
                ('status', models.CharField(choices=[('DIS', 'Disponível'), ('VEN', 'Vendida'), ('EMP', 'Empréstimo'), ('RES', 'Em Restauração'), ('ACE', 'Acervo Permanente')], default='DIS', max_length=3)),
                ('localizacao_atual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização Atual')),
                ('proprietario_atual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proprietário Atual')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('modo_aquisicao', models.CharField(blank=True, choices=[('COM', 'Compra'), ('DOA', 'Doação'), ('CMS', 'Comissão'), ('LEG', 'Legado')], max_length=3, null=True, verbose_name='Modo de Aquisição')),
                ('valor_seguro', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor do Seguro')),
                ('data_ultima_avaliacao', models.DateField(blank=True, null=True, verbose_name='Data da Última Avaliação')),
                ('estado_conservacao', models.CharField(blank=True, choices=[('EXC', 'Excelente'), ('BOM', 'Bom'), ('REG', 'Regular'), ('RUI', 'Ruim'), ('FRA', 'Fragmento')], max_length=3, null=True, verbose_name='Estado de Conservação')),
                ('relatorio_condicao', models.TextField(blank=True, null=True, verbose_name='Relatório de Condição')),
                ('historico_restauracao', models.TextField(blank=True, null=True, verbose_name='Histórico de Restauração')),
                ('data_ultima_higienizacao', models.DateField(blank=True, null=True, verbose_name='Data da Última Higienização')),
                ('recomendacoes_manuseio', models.TextField(blank=True, null=True, verbose_name='Recomendações de Manuseio')),
                ('imagem_principal', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Imagem Principal')),
                ('url_galeria_imagens', models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL da Galeria de Imagens')),
                ('copyright_imagem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Copyright da Imagem')),
                ('tipo_obra_digital', models.CharField(blank=True, choices=[('IMG', 'Imagem Estática'), ('GIF', 'Animação/GIF'), ('VID', 'Vídeo'), ('INT', 'Arte Interativa'), ('AR', 'Realidade Aumentada (AR)'), ('INSTALL', 'Instalação Digital')], max_length=7, null=True, verbose_name='Tipo de Obra Digital')),
                ('formato_imagem_estatica', models.CharField(blank=True, choices=[('JPEG', 'JPEG'), ('PNG', 'PNG'), ('WEBP', 'WEBP'), ('TIFF', 'TIFF'), ('RAW', 'RAW'), ('BMP', 'BMP'), ('SVG', 'SVG'), ('OUT', 'Outro (especificar)')], max_length=5, null=True, verbose_name='Formato (Imagem Estática)')),
                ('formato_animacao', models.CharField(blank=True, choices=[('GIF', 'GIF'), ('WEBP', 'WEBP (Animado)'), ('MP4', 'MP4 (Loop)'), ('OUT', 'Outro (especificar)')], max_length=5, null=True, verbose_name='Formato (Animação/GIF)')),
                ('formato_video', models.CharField(blank=True, choices=[('MP4', 'MP4'), ('MOV', 'MOV'), ('AVI', 'AVI'), ('WMV', 'WMV'), ('MKV', 'MKV'), ('OUT', 'Outro (especificar)')], max_length=5, null=True, verbose_name='Formato (Vídeo)')),
                ('formato_arquivo_exibicao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Formato do Arquivo de Exibição')),
                ('resolucao_dimensoes_px', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resolução/Dimensões (px)')),
                ('tamanho_arquivo_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tamanho do Arquivo (MB)')),
                ('duracao', models.DurationField(blank=True, null=True, verbose_name='Duração (HH:MM:SS)')),
                ('software_utilizado', models.TextField(blank=True, null=True, verbose_name='Software Utilizado')),
                ('hardware_utilizado', models.TextField(blank=True, null=True, verbose_name='Hardware Utilizado')),
                ('tecnica_glitch_aplicada', models.TextField(blank=True, null=True, verbose_name='Técnica de Glitch Aplicada')),
                ('codigo_fonte_algoritmo', models.TextField(blank=True, null=True, verbose_name='Código-Fonte/Algoritmo')),
                ('url_exibicao_online', models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL de Exibição Online')),
                ('dependencias_execucao', models.TextField(blank=True, null=True, verbose_name='Dependências de Execução')),
                ('instrucoes_exibicao', models.TextField(blank=True, null=True, verbose_name='Instruções de Exibição')),
                ('token_nft', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token NFT')),
                ('justificativa_ultima_alteracao', models.TextField(blank=True, help_text='Descreva brevemente o motivo da alteração feita.', null=True, verbose_name='Justificativa da Última Alteração')),
            ],
            options={
                'verbose_name': 'Obra de Arte',
                'verbose_name_plural': 'Obras de Arte',
                'ordering': ['-numero_registro', 'titulo'],
            },
        ),
    ]
