# Generated by Django 4.2.23 on 2025-08-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tessera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obradearte',
            name='imagem_principal',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='', verbose_name='Imagem Principal'),
        ),
    ]
